apiVersion: v1
kind: List
metadata: {}
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: messageboard
    name: dbserver
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: messageboard
        deployment: dbserver
    strategy: {}
    template:
      metadata:
        labels:
          app: messageboard
          deployment: dbserver
      spec:
        containers:
        - image: docker.io/postgres:15.1
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          env:
          - name: "POSTGRES_USER"
            valueFrom:
              secretKeyRef:
                name: "db-credentials"
                key: "username" 
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: "db-credentials"
                key: "password" 
          - name: "POSTGRES_DB"
            valueFrom:
              secretKeyRef:
                name: "db-credentials"
                key: "database" 

        #   volumeMounts:
        #     - mountPath: /var/lib/postgresql/data:z
        #       name: postgredb

        # volumes:
        #   - name: postgredb
        #     persistentVolumeClaim:
        #       claimName: postgres-pv-claim

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: messageboard
    name: dbserver
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: messageboard
      deployment: dbserver
